apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_USER: <base64_encode(DB_USER)>
  DB_PASSWORD: <base64_encode(DB_PASSWORD)>
  DB_DATABASE: <base64_encode(DB_DATABASE)>
